# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9cce828848146881c22d742e9a5ee7981e0df9d5c7a3cae69561b873db2167b4d62bf1601c80500392f9e64d6a2fc47fcfd1aa0e2ed970f02e1df9ab01faee

test:
  secret_key_base: 8b12f03c1e6a86742201a8cdb0e53d294d6d18395955c8ff729faa4cc8198943c70cb3b8d27b5a4d230617fbd6e31e42a85bc02ed4e47232c677d25af54f1acb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
